# Travis-CI Build for rugged
# see travis-ci.org for details

language: ruby

os:
  - linux
  - osx

# Ruby versions to test against
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - ruby-head
  - rbx-2

addons:
  apt:
    packages:
    - cmake
    - libssh2-1-dev
    - openssh-client
    - openssh-server

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./vendor/libgit2/script/install-deps-osx.sh; fi
  - bundle install --deployment

script: script/travisbuild
